/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package favouritebooks;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.LineNumberReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import sun.security.pkcs11.wrapper.Functions;

public class JFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame2
     */
    public JFrame2() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        add = new javax.swing.JPanel();
        categoryLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        authorNameLabel = new javax.swing.JLabel();
        awardLabel = new javax.swing.JLabel();
        ratingLabel = new javax.swing.JLabel();
        pageLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        awardTextField = new javax.swing.JTextField();
        authorNameTextField = new javax.swing.JTextField();
        titleTextField = new javax.swing.JTextField();
        pageTextField = new javax.swing.JTextField();
        categoryTextField = new javax.swing.JTextField();
        ratingCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descTextArea = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        ratingTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        resultSaveLbl = new javax.swing.JLabel();
        Delete = new javax.swing.JPanel();
        bookIDLabel = new javax.swing.JLabel();
        bookIDTxtField = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Search = new javax.swing.JPanel();
        searchNameLabel = new javax.swing.JLabel();
        searchNameTxtField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        clearBookNameBtn = new javax.swing.JButton();
        BookCover = new javax.swing.JPanel();
        searchIdLabel = new javax.swing.JLabel();
        searchIdTxtField = new javax.swing.JTextField();
        bookCoverLabel = new javax.swing.JLabel();
        searcBookCoverBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        clearBookCoverBtn = new javax.swing.JButton();
        listWithAuthorName = new javax.swing.JPanel();
        authorNameLbl = new javax.swing.JLabel();
        authorNameTxtField = new javax.swing.JTextField();
        displayWithAuthorBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        booksArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        descArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clearAuthorBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        listBooks = new javax.swing.JPanel();
        categoryLbl = new javax.swing.JLabel();
        categoryTxtField = new javax.swing.JTextField();
        booksWithCatBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        booksAreaWithCat = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        clearCatBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        booksOfYear = new javax.swing.JPanel();
        yearLbl = new javax.swing.JLabel();
        yearTxtField = new javax.swing.JTextField();
        numberBooksBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        numberBooksArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        yearLabell = new javax.swing.JLabel();
        clearYearBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        sortOfBooks = new javax.swing.JPanel();
        sortBtn = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        sortBookCatResult = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        clearSortBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add.setBackground(new java.awt.Color(153, 153, 255));

        categoryLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        categoryLabel.setText("Category :");

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setText("Title :");

        authorNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        authorNameLabel.setText("Author Name and Surname :");

        awardLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        awardLabel.setText("Award :");

        ratingLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ratingLabel.setText("Rating :");

        pageLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pageLabel.setText("Number of Pages :");

        descriptionLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        descriptionLabel.setText("Description :");

        yearLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yearLabel.setText("Year :");

        ratingCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ratingCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        ratingCombo.setToolTipText("");
        ratingCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingComboActionPerformed(evt);
            }
        });

        descTextArea.setColumns(20);
        descTextArea.setRows(5);
        jScrollPane1.setViewportView(descTextArea);

        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.setText("SAVE");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Book Record Screen");

        resultSaveLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add);
        add.setLayout(addLayout);
        addLayout.setHorizontalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addLayout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(157, 157, 157))
            .addGroup(addLayout.createSequentialGroup()
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(authorNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(awardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ratingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(yearTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(awardTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(authorNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(titleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(categoryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(pageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(ratingTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(ratingCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(resultSaveLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addLayout.setVerticalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(awardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(awardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ratingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(resultSaveLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jTabbedPane1.addTab("Add", add);

        Delete.setBackground(new java.awt.Color(153, 153, 255));

        bookIDLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bookIDLabel.setText("Book ID :");

        bookIDTxtField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Book Deletion Screen");

        javax.swing.GroupLayout DeleteLayout = new javax.swing.GroupLayout(Delete);
        Delete.setLayout(DeleteLayout);
        DeleteLayout.setHorizontalGroup(
            DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteLayout.createSequentialGroup()
                .addGroup(DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bookIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bookIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DeleteLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteLayout.createSequentialGroup()
                .addGap(0, 209, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        DeleteLayout.setVerticalGroup(
            DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete", Delete);

        Search.setBackground(new java.awt.Color(153, 153, 255));

        searchNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchNameLabel.setText("Book Name :");

        searchNameTxtField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        searchBtn.setText("SEARCH");
        searchBtn.setToolTipText("");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        resultArea.setColumns(10);
        resultArea.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        resultArea.setLineWrap(true);
        resultArea.setRows(5);
        resultArea.setBorder(new javax.swing.border.MatteBorder(null));
        resultArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(resultArea);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setText("Book Search Screen");

        clearBookNameBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clearBookNameBtn.setText("CLEAR");
        clearBookNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBookNameBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchLayout = new javax.swing.GroupLayout(Search);
        Search.setLayout(SearchLayout);
        SearchLayout.setHorizontalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchLayout.createSequentialGroup()
                        .addComponent(searchNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SearchLayout.createSequentialGroup()
                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearBookNameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(146, 146, 146))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(131, 131, 131))
        );
        SearchLayout.setVerticalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(clearBookNameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        jTabbedPane1.addTab("Search", Search);

        BookCover.setBackground(new java.awt.Color(153, 153, 255));

        searchIdLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchIdLabel.setText("Book ID :");

        searchIdTxtField.setBorder(null);

        searcBookCoverBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        searcBookCoverBtn.setText("ENTER");
        searcBookCoverBtn.setBorder(null);
        searcBookCoverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcBookCoverBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("BookCover Screen");

        clearBookCoverBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clearBookCoverBtn.setText("CLEAR");
        clearBookCoverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBookCoverBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BookCoverLayout = new javax.swing.GroupLayout(BookCover);
        BookCover.setLayout(BookCoverLayout);
        BookCoverLayout.setHorizontalGroup(
            BookCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookCoverLayout.createSequentialGroup()
                .addGroup(BookCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookCoverLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(searchIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(BookCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchIdTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(bookCoverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searcBookCoverBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addComponent(clearBookCoverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BookCoverLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        BookCoverLayout.setVerticalGroup(
            BookCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookCoverLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(BookCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BookCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searcBookCoverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBookCoverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(bookCoverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("BookCover", BookCover);

        listWithAuthorName.setBackground(new java.awt.Color(153, 153, 255));

        authorNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        authorNameLbl.setText("Author Name :");

        displayWithAuthorBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        displayWithAuthorBtn.setText("ENTER");
        displayWithAuthorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayWithAuthorBtnActionPerformed(evt);
            }
        });

        booksArea.setColumns(20);
        booksArea.setLineWrap(true);
        booksArea.setRows(5);
        jScrollPane3.setViewportView(booksArea);

        descArea.setColumns(20);
        descArea.setRows(5);
        jScrollPane6.setViewportView(descArea);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Book Names :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Descriptions :");

        clearAuthorBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearAuthorBtn.setText("CLEAR");
        clearAuthorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAuthorBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("Search Screen For Author's Books");

        javax.swing.GroupLayout listWithAuthorNameLayout = new javax.swing.GroupLayout(listWithAuthorName);
        listWithAuthorName.setLayout(listWithAuthorNameLayout);
        listWithAuthorNameLayout.setHorizontalGroup(
            listWithAuthorNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listWithAuthorNameLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(listWithAuthorNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listWithAuthorNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addComponent(authorNameTxtField)
                    .addComponent(jScrollPane3)
                    .addGroup(listWithAuthorNameLayout.createSequentialGroup()
                        .addComponent(displayWithAuthorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearAuthorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listWithAuthorNameLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(109, 109, 109))
        );
        listWithAuthorNameLayout.setVerticalGroup(
            listWithAuthorNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listWithAuthorNameLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addGap(50, 50, 50)
                .addGroup(listWithAuthorNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(authorNameTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(authorNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(listWithAuthorNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayWithAuthorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearAuthorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(listWithAuthorNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(46, 46, 46)
                .addGroup(listWithAuthorNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ListWithAuthorName", listWithAuthorName);

        listBooks.setBackground(new java.awt.Color(153, 153, 255));

        categoryLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        categoryLbl.setText("Category Name :");

        booksWithCatBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        booksWithCatBtn.setText("ENTER");
        booksWithCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksWithCatBtnActionPerformed(evt);
            }
        });

        booksAreaWithCat.setColumns(20);
        booksAreaWithCat.setRows(5);
        jScrollPane4.setViewportView(booksAreaWithCat);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("BOOK TITLES");

        clearCatBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearCatBtn.setText("CLEAR");
        clearCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCatBtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setText("Search Screen By Category");

        javax.swing.GroupLayout listBooksLayout = new javax.swing.GroupLayout(listBooks);
        listBooks.setLayout(listBooksLayout);
        listBooksLayout.setHorizontalGroup(
            listBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listBooksLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(listBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(listBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4)
                        .addGroup(listBooksLayout.createSequentialGroup()
                            .addComponent(categoryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(listBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(listBooksLayout.createSequentialGroup()
                                    .addComponent(booksWithCatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(clearCatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(categoryTxtField)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listBooksLayout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(166, 166, 166))
        );
        listBooksLayout.setVerticalGroup(
            listBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listBooksLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel12)
                .addGap(51, 51, 51)
                .addGroup(listBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(categoryTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(categoryLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(listBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clearCatBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(booksWithCatBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ListBooks", listBooks);

        booksOfYear.setBackground(new java.awt.Color(153, 153, 255));

        yearLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yearLbl.setText("Enter Year :");

        numberBooksBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numberBooksBtn.setText("ENTER");
        numberBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBooksBtnActionPerformed(evt);
            }
        });

        numberBooksArea.setColumns(20);
        numberBooksArea.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        numberBooksArea.setRows(5);
        jScrollPane5.setViewportView(numberBooksArea);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("The Number Of Books :");

        yearLabell.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        clearYearBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearYearBtn.setText("CLEAR");
        clearYearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearYearBtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("Number Of Books By Year Screen");
        jLabel11.setToolTipText("");

        javax.swing.GroupLayout booksOfYearLayout = new javax.swing.GroupLayout(booksOfYear);
        booksOfYear.setLayout(booksOfYearLayout);
        booksOfYearLayout.setHorizontalGroup(
            booksOfYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksOfYearLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(booksOfYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(booksOfYearLayout.createSequentialGroup()
                        .addGroup(booksOfYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(booksOfYearLayout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearLabell, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(367, Short.MAX_VALUE))
                    .addGroup(booksOfYearLayout.createSequentialGroup()
                        .addGroup(booksOfYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(booksOfYearLayout.createSequentialGroup()
                                .addComponent(numberBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(clearYearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(booksOfYearLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        booksOfYearLayout.setVerticalGroup(
            booksOfYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, booksOfYearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(yearTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(booksOfYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clearYearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberBooksBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(92, 92, 92)
                .addComponent(jLabel8)
                .addGroup(booksOfYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(booksOfYearLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(yearLabell, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(booksOfYearLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("NumberOfBooksWithYear", booksOfYear);

        sortOfBooks.setBackground(new java.awt.Color(153, 153, 255));

        sortBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sortBtn.setText("SORT");
        sortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortBtnActionPerformed(evt);
            }
        });

        sortBookCatResult.setColumns(20);
        sortBookCatResult.setRows(5);
        jScrollPane7.setViewportView(sortBookCatResult);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel10.setText("Sorting Screen");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("↓ Less To More ↓ ");

        clearSortBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearSortBtn.setText("CLEAR");
        clearSortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSortBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sortOfBooksLayout = new javax.swing.GroupLayout(sortOfBooks);
        sortOfBooks.setLayout(sortOfBooksLayout);
        sortOfBooksLayout.setHorizontalGroup(
            sortOfBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sortOfBooksLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(225, 225, 225))
            .addGroup(sortOfBooksLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(sortOfBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(sortOfBooksLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addGroup(sortOfBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sortBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearSortBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        sortOfBooksLayout.setVerticalGroup(
            sortOfBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortOfBooksLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel10)
                .addGap(25, 25, 25)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sortOfBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sortOfBooksLayout.createSequentialGroup()
                        .addComponent(sortBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(clearSortBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sort", sortOfBooks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        title = titleTextField.getText();
        category = categoryTextField.getText();
        authorNameSurname = authorNameTextField.getText();
        award = awardTextField.getText();
        ratingString = ratingTextField.getText();
        year = yearTextField.getText();
        page = pageTextField.getText();
        description = descTextArea.getText();

        FileWriter writer = null;
        try {
            File file = new File("favouritebooks.txt");
            writer = new FileWriter(file, true);
            try (PrintWriter printWriter = new PrintWriter(writer)) {
                bookId = readFile(file) + 1;
                bookID = String.valueOf(bookId);
                String string = (bookID + "," + title + "," + category + "," + authorNameSurname + "," + award + "," + ratingString
                        + "," + year + "," + page + "," + description);
                printWriter.println(string);
                
                
                resultSaveLbl.setText("Saved the book successfully!");
            }

        } catch (IOException e) {
            System.out.println("Error");
        } finally {
            try {
                writer.close();

                setVisible(false);
                new JFrame2().setVisible(true);
            } catch (IOException e) {

            }
        }

        /* try {
         
            
            FileWriter writer = new FileWriter("favouritebooks.txt", true);
            writer.write(bookID + "," + title + "," + category + "," + authorNameSurname + "," + award + "," + ratingString
                    + "," + year + "," + page + "," + description);
            writer.write(System.getProperty("line.separator"));
            writer.close();

            setVisible(false);
            new JFrame2().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }*/

    }//GEN-LAST:event_addButtonActionPerformed

    private void ratingComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingComboActionPerformed
        // TODO add your handling code here:
        rating = ratingCombo.getSelectedIndex();
        ratingTextField.setText(String.valueOf(rating + 1));
    }//GEN-LAST:event_ratingComboActionPerformed


    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:

        try {
            File file = new File("D:\\NetBeansProjects\\FavouriteBooks\\favouritebooks.txt");

            int deleteLine = Integer.parseInt(bookIDTxtField.getText());

            File tempFile = new File("D:\\NetBeansProjects\\FavouriteBooks\\temp.txt");
            LineNumberReader lineNumberReader;
            try (BufferedReader reader = new BufferedReader(new FileReader("D:\\NetBeansProjects\\FavouriteBooks\\favouritebooks.txt"))) {
                PrintWriter writer = new PrintWriter(new FileWriter(tempFile));
                lineNumberReader = new LineNumberReader(new FileReader(file));
                while (lineNumberReader.getLineNumber() != deleteLine) {
                    String line = lineNumberReader.readLine();
                    if (line == null) {
                        JOptionPane.showMessageDialog(this, "Error");
                        break;
                    } else if (lineNumberReader.getLineNumber() != deleteLine) {
                        writer.println(line);
                        writer.flush();
                    } else if (lineNumberReader.getLineNumber() == deleteLine) {
                        JOptionPane.showMessageDialog(this, "Deleted");

                    }

                }
                writer.close();
            }
            lineNumberReader.close();
            file.delete();
            tempFile.renameTo(file);

        } catch (FileNotFoundException e) {
            Logger.getLogger(Functions.class.getName()).log(Level.SEVERE, null, e);
        } catch (IOException e) {
            Logger.getLogger(Functions.class.getName()).log(Level.SEVERE, null, e);
        } finally {

        }


    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:

        String filepath = "favouritebooks.txt";
        String search = searchNameTxtField.getText();

        try {
            Scanner x = new Scanner(new File(filepath));

            while (x.hasNext()) {

                String[] booksInfo = x.nextLine().split(",");
                title = booksInfo[1];

                if (search.equals(title)) {

                    resultArea.setText(resultArea.getText() + "Book ID:" + booksInfo[0] + "\n");
                    resultArea.setText(resultArea.getText() + "Book Name:" + booksInfo[1] + "\n");
                    resultArea.setText(resultArea.getText() + "Book Category:" + booksInfo[2] + "\n");
                    resultArea.setText(resultArea.getText() + "Book Author:" + booksInfo[3] + "\n");
                    resultArea.setText(resultArea.getText() + "Book Award:" + booksInfo[4] + "\n");
                    resultArea.setText(resultArea.getText() + "Book Rating:" + booksInfo[5] + "\n");
                    resultArea.setText(resultArea.getText() + "Book Year:" + booksInfo[6] + "\n");
                    resultArea.setText(resultArea.getText() + "Book Page:" + booksInfo[7] + "\n");
                    resultArea.setText(resultArea.getText() + "Book Description:" + booksInfo[8]);

                }
                
            }

        } catch (Exception e) {

            System.out.println("Error Message");

        }


    }//GEN-LAST:event_searchBtnActionPerformed

    private void searcBookCoverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcBookCoverBtnActionPerformed
        // TODO add your handling code here:
        String searchId = searchIdTxtField.getText();
        int srcId = Integer.parseInt(searchId);
        ImageIcon img1 = new ImageIcon("D:\\NetBeansProjects\\FavouriteBooks\\src\\Images\\Book1Cover.jpg");
        ImageIcon img2 = new ImageIcon("D:\\NetBeansProjects\\FavouriteBooks\\src\\Images\\Book2Cover.jpg");
        ImageIcon img3 = new ImageIcon("D:\\NetBeansProjects\\FavouriteBooks\\src\\Images\\Book3Cover.jpg");
        ImageIcon img4 = new ImageIcon("D:\\NetBeansProjects\\FavouriteBooks\\src\\Images\\Book4Cover.jpg");
        ImageIcon img5 = new ImageIcon("D:\\NetBeansProjects\\FavouriteBooks\\src\\Images\\Book5Cover.jpg");
        ImageIcon noimage = new ImageIcon("D:\\NetBeansProjects\\FavouriteBooks\\src\\Images\\noimage.jpg");

        if (srcId == 1) {
            bookCoverLabel.setIcon(img1);
        } else if (srcId == 2) {
            bookCoverLabel.setIcon(img2);
        } else if (srcId == 3) {
            bookCoverLabel.setIcon(img3);
        } else if (srcId == 4) {
            bookCoverLabel.setIcon(img4);
        } else if (srcId == 5) {
            bookCoverLabel.setIcon(img5);
        } else {
            bookCoverLabel.setIcon(noimage);
        }


    }//GEN-LAST:event_searcBookCoverBtnActionPerformed

    private void displayWithAuthorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayWithAuthorBtnActionPerformed
        // TODO add your handling code here:

        String filepath = "favouritebooks.txt";
        String authorInfo = authorNameTxtField.getText();

        try {
            Scanner x = new Scanner(new File(filepath));

            while (x.hasNext()) {

                String[] booksInfo = x.nextLine().split(",");
                authorNameSurname = booksInfo[3];

                if (authorInfo.equals(authorNameSurname)) {
                    booksArea.setText(booksArea.getText() + "\n" + booksInfo[1]);
                    booksArea.setText(booksArea.getText() + "\n");
                    descArea.setText(descArea.getText() + "\n" + booksInfo[8]);
                    descArea.setText(descArea.getText() + "\n");
                }
                
            }

        } catch (Exception e) {

            System.out.println("Error Message");

        }


    }//GEN-LAST:event_displayWithAuthorBtnActionPerformed

    private void booksWithCatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksWithCatBtnActionPerformed
        // TODO add your handling code here:
        String filepath = "favouritebooks.txt";
        String categoryInfo = categoryTxtField.getText();
        String[] booksInfo = new String[DO_NOTHING_ON_CLOSE];

        try {
            Scanner x = new Scanner(new File(filepath));

            while (x.hasNext()) {

                booksInfo = x.nextLine().split(",");
                category = booksInfo[2];

                if (categoryInfo.equals(category)) {
                    booksAreaWithCat.setText(booksAreaWithCat.getText() + "\n" + booksInfo[1]);
                    booksAreaWithCat.setText(booksAreaWithCat.getText() + "\n");
                }
                
            }

        } catch (Exception e) {
            System.out.println("Error Message");
        }
    }//GEN-LAST:event_booksWithCatBtnActionPerformed

    private void numberBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBooksBtnActionPerformed
        // TODO add your handling code here:
        String filepath = "favouritebooks.txt";
        String enterYear = yearTxtField.getText();
        int count = 0;

        try {
            Scanner x = new Scanner(new File(filepath));

            while (x.hasNext()) {

                String[] booksInfo = x.nextLine().split(",");
                year = booksInfo[6];

                if (enterYear.equals(year)) {
                    count++;
                    yearLabell.setText(enterYear);
                }
                
            }

            numberBooksArea.setText(numberBooksArea.getText() + "\n" + count);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_numberBooksBtnActionPerformed

    private void clearBookNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBookNameBtnActionPerformed
        // TODO add your handling code here:
        searchNameTxtField.setText("");
        resultArea.setText("");
    }//GEN-LAST:event_clearBookNameBtnActionPerformed

    private void clearAuthorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAuthorBtnActionPerformed
        // TODO add your handling code here:
        authorNameTxtField.setText("");
        booksArea.setText("");
        descArea.setText("");
    }//GEN-LAST:event_clearAuthorBtnActionPerformed

    private void clearCatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCatBtnActionPerformed
        // TODO add your handling code here:

        categoryTxtField.setText("");
        booksAreaWithCat.setText("");
    }//GEN-LAST:event_clearCatBtnActionPerformed

    private void clearYearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearYearBtnActionPerformed
        // TODO add your handling code here:
        yearTxtField.setText("");
        numberBooksArea.setText("");
        yearLabell.setText("");
    }//GEN-LAST:event_clearYearBtnActionPerformed

    private void sortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortBtnActionPerformed
        // TODO add your handling code here:
        String filepath = "favouritebooks.txt";
        ArrayList<String> list = new ArrayList<>();
        String[] booksInfo = new String[DO_NOTHING_ON_CLOSE];
        String[] book = new String[DO_NOTHING_ON_CLOSE];
        try {
            Scanner x = new Scanner(new File(filepath));

            while (x.hasNext()) {

                booksInfo = x.nextLine().split(",");
                category = booksInfo[2];

                list.add("Rating :" + booksInfo[5] + "\n"+"Book Name : " + booksInfo[1] + " --"+" Category : " + category);

                Collections.sort(list);

            }

            for (String s : list) {

                sortBookCatResult.setText(sortBookCatResult.getText() + s + "\n");
            }

        } catch (Exception e) {
            System.out.println("Error Message");
        }

    }//GEN-LAST:event_sortBtnActionPerformed

    private void clearSortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSortBtnActionPerformed
        // TODO add your handling code here:
        sortBookCatResult.setText("");
    }//GEN-LAST:event_clearSortBtnActionPerformed

    private void clearBookCoverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBookCoverBtnActionPerformed
        // TODO add your handling code here:
        searchIdTxtField.setText("");
        
    }//GEN-LAST:event_clearBookCoverBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookCover;
    private javax.swing.JPanel Delete;
    private javax.swing.JPanel Search;
    private javax.swing.JPanel add;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel authorNameLabel;
    private javax.swing.JLabel authorNameLbl;
    private javax.swing.JTextField authorNameTextField;
    private javax.swing.JTextField authorNameTxtField;
    private javax.swing.JLabel awardLabel;
    private javax.swing.JTextField awardTextField;
    private javax.swing.JLabel bookCoverLabel;
    private javax.swing.JLabel bookIDLabel;
    private javax.swing.JTextField bookIDTxtField;
    private javax.swing.JTextArea booksArea;
    private javax.swing.JTextArea booksAreaWithCat;
    private javax.swing.JPanel booksOfYear;
    private javax.swing.JButton booksWithCatBtn;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel categoryLbl;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JTextField categoryTxtField;
    private javax.swing.JButton clearAuthorBtn;
    private javax.swing.JButton clearBookCoverBtn;
    private javax.swing.JButton clearBookNameBtn;
    private javax.swing.JButton clearCatBtn;
    private javax.swing.JButton clearSortBtn;
    private javax.swing.JButton clearYearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextArea descArea;
    private javax.swing.JTextArea descTextArea;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton displayWithAuthorBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel listBooks;
    private javax.swing.JPanel listWithAuthorName;
    private javax.swing.JTextArea numberBooksArea;
    private javax.swing.JButton numberBooksBtn;
    private javax.swing.JLabel pageLabel;
    private javax.swing.JTextField pageTextField;
    private javax.swing.JComboBox<String> ratingCombo;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JTextField ratingTextField;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JLabel resultSaveLbl;
    private javax.swing.JButton searcBookCoverBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel searchIdLabel;
    private javax.swing.JTextField searchIdTxtField;
    private javax.swing.JLabel searchNameLabel;
    private javax.swing.JTextField searchNameTxtField;
    private javax.swing.JTextArea sortBookCatResult;
    private javax.swing.JButton sortBtn;
    private javax.swing.JPanel sortOfBooks;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JLabel yearLabell;
    private javax.swing.JLabel yearLbl;
    private javax.swing.JTextField yearTextField;
    private javax.swing.JTextField yearTxtField;
    // End of variables declaration//GEN-END:variables

    String title;
    String category;
    String authorNameSurname;
    String award;
    int rating;
    String ratingString;
    String year;
    String page;
    String description;
    String bookID;
    int bookId;

    public static int readFile(File file) throws FileNotFoundException, IOException {
        LineNumberReader reader = null;

        try {
            reader = new LineNumberReader(new FileReader(file));
            while ((reader.readLine()) != null);
            return reader.getLineNumber();
        } catch (Exception e) {
            return -1;
        } finally {
            if (reader != null) {
                reader.close();
            }
        }

    }

}
